### ISSUE TITLE
Radar that was filed for `get_sha()`?

### ISSUE THREAD

**Issue by pkamb** [drewcrawford/CaveJohnson#1]
```
# rdar://17923022
def get_sha():
    sourceLogPath = os.path.join(os.environ["XCS_OUTPUT_DIR"], "sourceControl.log")
    with open(sourceLogPath) as sourceFile:
        sourceLog = sourceFile.read()
        match = re.search('"DVTSourceControlLocationRevisionKey"\s*\:\s*"(.*)"', sourceLog)
        if not match:
            raise Exception("No sha match in file.  Please file a bug at http://github.com/drewcrawford/cavejohnson and include the contents of %s" % sourceLogPath)
        return match.groups()[0]
    assert False
```

Would you mind filing an [OpenRadar](http://openradar.appspot.com/) and/or posting what that issue is?

**Comment by drewcrawford** [comment]
It's about what you'd expect, a feature request for a public API to get the sha.

As you can see here, the best implementation that I could come up with was parsing an undocumented log file, which is not *exactly* future-proof.

**Comment by pkamb** [comment]
Cool, thanks. The points here are yours if you want them, otherwise I'll answer in a day or two:  
http://stackoverflow.com/questions/28620681/how-to-get-sha-of-commit-for-xcode-bot-run-script-trigger-updating-status-of
