### ISSUE TITLE
Not finding my provision profile error.

### ISSUE THREAD

**Issue by prince-ugwuh-volusion** [drewcrawford/CaveJohnson#10]
Hey Drew, 

Thanks for creating a very nice tool. I'm having an issue with getting the script to use the right provision profile. Currently running in Xcode 6.1.1 on OS X Server Yosemite current released version.

I'm adding .. for the pre trigger action 
```
PATH=/Library/Frameworks/Python.framework/Versions/3.4/bin:$PATH
cavejohnson setBuildNumber --plist-path "$XCS_SOURCE_DIR"/iOSApp/myApp/Info.plist
cavejohnson installMobileProvision --provisioning-profile "$XCS_SOURCE_DIR"/iOSApp/myProvision.mobileprovision
```

from the trigger-log I'm getting no message of success or failure BUT in the post trigger-log, where I'm trying to upload to new TestFlight, I'm getting the message 
```
...
[2015-03-03 13:38:20 CST] <main> ERROR: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.volusion.store [Payload/Volusion.app] is invalid. [Missing code-signing certificate.] For more information, visit the iOS Developer Portal."
[2015-03-03 13:38:20 CST] <main> DBG-X: The error code is: 1102
[2015-03-03 13:38:20 CST] <main>  INFO: Done performing authentication.

Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/pp/zb040xyd461gv7hnp1r3xrxw000087/T/tmpajh0hgn1/package.itmsp - Error Messages:
		ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.volusion.store [Payload/Volusion.app] is invalid. [Missing code-signing certificate.] For more information, visit the iOS Developer Portal."
[2015-03-03 13:38:20 CST] <main> DBG-X: Returning 1
Working in path /var/folders/pp/zb040xyd461gv7hnp1r3xrxw000087/T/tmpajh0hgn1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/cavejohnson", line 9, in <module>
    load_entry_point('cavejohnson==1.0.1', 'console_scripts', 'cavejohnson')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 566, in main_func
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 117, in uploadITMS
    upload_itunesconnect(args.itunes_app_id, args.itunes_username, args.itunes_password, args.ipa_path)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cavejohnson/__init__.py", line 175, in upload_itunesconnect
    "-m", "upload", "-apple_id", itunes_app_id, "-u", itunes_username, "-p", itunes_password, "-f", packagepath])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/MacOS/itms/bin/iTMSTransporter', '-m', 'upload', '-apple_id', '123456', '-u', 'prince-ugwuh@volusion.com', '-p', '*hidden*', '-f', '/var/folders/pp/zb040xyd461gv7hnp1r3xrxw000087/T/tmpajh0hgn1/package.itmsp']' returned non-zero exit status 1
```

Note: I have removed some information.

Any Ideas? The provision file I included in the project I pulled from what Xcode was about to send to the server from the organizer.

**Comment by drewcrawford** [comment]
> [Missing code-signing certificate.]

did you install the code signing certificate?

**Comment by prince-ugwuh-volusion** [comment]
that would be the file that has the cer extension right? if so then yes.

**Comment by drewcrawford** [comment]
It should be sufficient for it to appear in your system keychain, with the access controls disabled as described in the README.

Assuming that's been done, it's possible that you've installed a certificate that doesn't match the provisioning profile...

**Comment by drewcrawford** [comment]
> That would be the file that has the cer extension right? if so then yes.

Actually no.  That only has the public portion.  You need to export it and its key to a .p12 with Keychain Access, and import that on the server.

**Comment by prince-ugwuh-volusion** [comment]
ah ok. giving that a try... I'll post back if I see anymore issues. Thanks!

**Comment by prince-ugwuh-volusion** [comment]
Ok I'm still getting that issue. I feel its not even calling the pre trigger script. Everything looks correct ... the p12 file is in and I selected the radio button.

**Comment by drewcrawford** [comment]
Well it is easy to check if the pre-trigger script is running... just append `echo "whatever"` on the end.  In true Unix fashion, CJ is usually quiet if it can avoid it, so absence of log is not evidence of absence.

What's the output of

```bash
$ sudo -u _xcsbuildd xcodebuild -workspace [workspace] -scheme [SchemeName] archive
```

?

(You may have to chown some directories to `_xcsbuildd` to test this.)

**Comment by drewcrawford** [comment]
Digging into this more, sources confirm that error message from iTMS is consistent with distributing an IPA signed for *development* to iTunesConnect.  Which it obviously won't take.

My suspicion is your provisioning profile is set to automatic, which can cause XCS to silently sign for development even when the code signing settings say to sign for distribution.

Other possibilities include the build settings not set to sign for distribution to begin with.

**Comment by prince-ugwuh-volusion** [comment]
Ok ... your suspicion is correct! So provisioning profile is set to something else not automatic. I set it to the correct distribution. And it uploaded with a warning about beta entitlement. But I know where to go from here. This is a good start. Thanks Drew for helping me debug this issue. Appreciate your feedback immensely.
