### ISSUE TITLE
This API can only be accessed with username and password Basic Auth

### ISSUE THREAD

**Issue by pkamb** [drewcrawford/CaveJohnson#2]
After running `sudo -u _xcsbuildd cavejohnson setGithubCredentials` and using a generated GitHub Auth token I get:

 > 403: This API can only be accessed with username and password Basic Auth

Would be very nice to add support for Auth tokens.

**Comment by drewcrawford** [comment]
What *exactly* is the desired behavior here?  Are you going to

1.  Generate your own token all by yourself
2.  "Use the source, Luke" to figure out what permissions the token needs
3.  You want CaveJohnson to store it?

**Comment by pkamb** [comment]
Desired behavior would be to generate and use a Github app "Personal access token" for these requests rather than typing my user Github password into the tool.

https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by drewcrawford** [comment]
As a workaround you can 

```bash
echo "token" > /var/_xcsbuildd/githubcredentials
```

There's no particular reason why this couldn't be a cavejohnson command, or an arg to `setGithubCredentials`.  I'll put it on my list for the next release, but feel free to submit a PR if you want it faster.
