### ISSUE TITLE
/bin/sh failed with exist code 1

### ISSUE THREAD

**Issue by yadah** [drewcrawford/CaveJohnson#20]
In the log files I am getting errors when the trigger tries to run the cavejohnson commands

/var/folders/dc/n_9ptdmj19nd627n6vb109z4000086/T/A53E2CD2-D541-4FC2-BC40-258B4BFC69CE-14314-0000102D8E057821: line 4: cavejohnson: command not found
/var/folders/dc/n_9ptdmj19nd627n6vb109z4000086/T/A53E2CD2-D541-4FC2-BC40-258B4BFC69CE-14314-0000102D8E057821: line 5: cavejohnson: command not found

My script

#!/bin/bash
PATH=/Library/Frameworks/Python.framework/Versions/3.4/bin:$PATH
cavejohnson setBuildNumber --plist-path ./iOS/Info.plist
cavejohnson installMobileProvision --provisioning-profile ./iOS/HonestDollarAdhoc.mobileprovision

**Comment by drewcrawford** [comment]
what's

`ls /Library/Frameworks/Python.framework/Versions/3.4/bin` ?
