### ISSUE TITLE
Xcode7 integration?

### ISSUE THREAD

**Issue by axialraf** [drewcrawford/CaveJohnson#23]
Hi, I use cavejohnson in Jenkins. We've just moved to xcode7, but now we're getting this:

```
++ /usr/local/bin/cavejohnson uploadiTunesConnect --itunes-app-id BLAH --itunes-username BLAH --itunes-password BLAH --ipa-path APPNAME-4823-892cf23d-APPSTORE.ipa
Working in path /var/folders/4r/h012hsjj59qcxzgc87kkfmvh0000gp/T/tmppqkjjr62
Traceback (most recent call last):
  File "/usr/local/bin/cavejohnson", line 11, in <module>
    sys.exit(main_func())
  File "/usr/local/lib/python3.5/site-packages/cavejohnson/__init__.py", line 600, in main_func
    args.func(args)
  File "/usr/local/lib/python3.5/site-packages/cavejohnson/__init__.py", line 117, in uploadITMS
    upload_itunesconnect(args.itunes_app_id, args.itunes_username, args.itunes_password, args.ipa_path)
  File "/usr/local/lib/python3.5/site-packages/cavejohnson/__init__.py", line 175, in upload_itunesconnect
    "-m", "upload", "-apple_id", itunes_app_id, "-u", itunes_username, "-p", itunes_password, "-f", packagepath])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/share/iTMSTransporter.woa/iTMSTransporter'
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
```

**Comment by drewcrawford** [comment]
It looks like the path of iTMSTransporter changed to `Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter`.  It *may* be as simple as changing the path [here](https://github.com/drewcrawford/CaveJohnson/blob/master/cavejohnson/__init__.py#L176), although I can't confirm.

With respect to the issue title, going forward, I'm using CJ1 on XC6 systems and I'm doing XC7 in CJ2, although CJ2 does not yet support iTunes uploading and so doesn't (yet) solve your problem.  You may want to file a feature request in that project, as I don't think there's one already.

That aside, if a plausible patch appeared and someone claimed it fixed XC7 issues, I would be happy to merge it here.

**Comment by axialraf** [comment]
Thanks Drew. Well, two things. Based on the error I did try to get past it by changing the path, but then I got a java not found error, once I got past that, I got this one:
```Error: Could not find or load main class com.apple.transporter.Application```
So I'm at a loss. Hopefully that XC7-fix patch will do the trick.
As far as CJ2 goes, I tried to download it by going to https://cavejohnsonreleases.s3.amazonaws.com/files.html but I always get a blank page there. 

Thanks!

**Comment by drewcrawford** [comment]
So when I run `/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter` in Xcode 7.0.1, I get this output:

```
[2015-09-30 18:10:36 CDT] <main>  INFO: Transporter is skipping bundle update check: Already checked recently.
usage: iTMSTransporter [-help <arg> | -info | -m <arg> | -version]   [-o <arg>] [-v
       <arg>]  [-WONoPause <arg>] [-Xmx1024m]
iTMSTransporter : iTunes Store Transporter 1.8.6
 -help <arg>        Show this help.  If a mode value is specified, show help specific
                    to that mode.
 -info              The -info option should be used by itself and returns the
                    copyright notice and acknowledgements.
 -m <arg>           The -m option specifies the tool's mode.  The valid values are:
                    verify, upload, provider, diagnostic, lookupMetadata, status,
                    statusAll, queryTickets, generateSchema, transferTest,
                    downloadMetadataGuides, iTunesExtraQCDownload, iTunesLPQCDownload,
                    iTunesExtraTemplate, iTunesLPTemplate, listReports, requestReport
 -o <arg>           The -o option specifies the directory and filename you want to use
                    to log output information.  By default, Transporter logs output
                    information to standard out. If you specify a filename,
                    Transporter logs the output to the specified file, as well as to
                    standard out.
 -v <arg>           The -v option specifies the level of logging.  The five values
                    are: off, detailed, informational, critical, eXtreme.
 -version           The -version option should be used by itself and returns the
                    version of the tool.
 -WONoPause <arg>   The -WONoPause option is only valid on Windows and its value can
                    be 'true' or 'false'.  If an error occurs during script execution,
                    the process idles because the message 'Press any key...' is
                    displayed on the console and the system awaits a keypress. To
                    avoid this behavior, set this property to true
 -Xmx1024m          Specifies that you want to change the Java Virtual Machine's (JVM)
                    allocated memory by increasing the JVM heap size.  By default,
                    Transporter uses a 512MB heap size. You can use the -Xmx1024m
                    option to specify a 1-gigabyte (GB) heap size. Apple recommends,
                    if needed, increasing the heap size to 1024MB by specifying the
                    -Xmx1024 option and adjusting as needed.
```

Note that my java version is:

```bash
$ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

Do you see something different?

> As far as CJ2 goes, I tried to download it by going to https://cavejohnsonreleases.s3.amazonaws.com/files.html but I always get a blank page there.

Do you have JS disabled?  I think that index page is created via JS.  You're welcome to open an issue in CJ2 if you can't load that page or if you can think of some better way to display the contents of an S3 bucket.

**Comment by axialraf** [comment]
Thanks Drew.
Looking at the source for  https://cavejohnsonreleases.s3.amazonaws.com/files.html
, it’s complaining that https://rgrp.github.io/s3-bucket-listing/list.js
 has permanently moved, I wonder if that’s what causing the issue.


When I run iTMSTransporter, I get this:


$ /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter
An error occurred while starting bundles for the software update process.  Transporter will try to continue.  Unresolved constraint in bundle com.apple.jingle.leghorn [1]: Unable to resolve 1.0: missing requirement [1.0] package; (package=com.sun.xml.bind.v2)
An error occurred while starting bundles for the software update process.  Transporter will try to continue.  Unresolved constraint in bundle com.apple.transporter [3]: Unable to resolve 3.0: missing requirement [3.0] package; (&(package=com.apple.itunes.epubtoolkit)(version>=1.8.3)(version<=1.8.3)) [caused by: Unable to resolve 1.0: missing requirement [1.0] package; (package=com.sun.xml.bind.v2)]
An error occurred while starting bundles for the software update process.  Transporter will try to continue.  Unresolved constraint in bundle com.apple.transporter.softwaresupport [6]: Unable to resolve 6.0: missing requirement [6.0] package; (&(package=com.apple.                                                                      jingle.leghorn.software)(version>=1.8.3)(version<=1.8.3)) [caused by: Unable to resolve 1.0: missing requirement [1.0] package; (package=com.sun.xml.bind.v2)]
An error occurred while starting bundles for the software update process.  Transporter will try to continue.  Unresolved constraint in bundle com.apple.transporter.updater [8]:    Unable to resolve 8.0: missing requirement [8.0] package; (&(package=com.apple.transporter.log)(version>=1.8.3)(version<=1.8.3)) [caused by: Unable to resolve 3.0: missing requirement [3.0] package; (&(package=com.apple.itunes.epubtoolkit)(version>=1.8.3)(version  <=1.8.3)) [caused by: Unable to resolve 1.0: missing requirement [1.0] package; (package =com.sun.xml.bind.v2)]]
[2015-10-01 10:44:02 EDT] <main>  INFO: Transporter is searching for updated software components.
[2015-10-01 10:44:04 EDT] <main>  INFO: Transporter has detected that new software components exist; updating.
[2015-10-01 10:44:04 EDT] <main> DEBUG: Analyzing remote bundle resource org.apache.http components.httpclient...
[2015-10-01 10:44:07 EDT] <main> DEBUG:   ... updated bundle successfully retrieved.
[2015-10-01 10:44:07 EDT] <main> DEBUG: Analyzing remote bundle resource org.apache.httpcomponents.httpcore...
[2015-10-01 10:44:09 EDT] <main> DEBUG:   ... updated bundle successfully retrieved.
[2015-10-01 10:44:09 EDT] <main> DEBUG: Analyzing remote bundle resource com.springsource.org.apache.commons.beanutils...
[2015-10-01 10:44:10 EDT] <main> DEBUG:   ... updated bundle successfully retrieved.



But now I’m getting the same output as you. I’ll try cj again. Thank you!


Raf Cabezas | Mobile App Development

O: 919.576.9988

**Comment by drewcrawford** [comment]
> Looking at the source for  https://cavejohnsonreleases.s3.amazonaws.com/files.html
> , it’s complaining that https://rgrp.github.io/s3-bucket-listing/list.js
>  has permanently moved, I wonder if that’s what causing the issue.

Thanks for that report.  Refresh and let me know if fixed?

**Comment by axialraf** [comment]
Yes, it’s fixed. Thank you Drew.




Raf Cabezas | Mobile App Development

O: 919.576.9988

**Comment by drewcrawford** [comment]
Thanks, reported it upstream as well.  Closing since it doesn't seem like there's any issue outstanding anymore.
